import { Injectable } from '@angular/core';
import { Observable } from "rxjs";

@Injectable({
  providedIn: 'root'
})
export class RestDataService {
  private usersData = [
    {
      userId: '1',
      userName : 'Иванов Иван Иванович',
      userBirthDate : new Date(2011, 10, 11),
      userOMS : '1111111111111111',
      userAppointment : [
        {
          appId: 1,
          specId: '1',
          userId: '1',
          appDate: new Date(2023, 8, 26, 10, 0),
        },
        {
          appId: 2,
          specId: '1',
          userId: '1',
          appDate: new Date(2023, 9, 3, 10, 0),
        }
      ],
    },
    {
      userId: '2',
      userName : 'Алексеев Алексей Алексеевич',
      userBirthDate : new Date(1922, 11, 22),
      userOMS : '2222222222222222',
      userAppointment : [
        { appId: 1,
          specId: '1',
          userId: '2',
          appDate: new Date(2023, 8, 26, 10, 0),
        },
        { appId: 2,
          specId: '1',
          userId: '2',
          appDate: new Date(2023, 9, 3, 10, 0),
        }
      ],
    },
    {
      userId: '3',
      userName : 'Петров Петр Петрович',
      userBirthDate : new Date(1990, 0, 1),
      userOMS : '3333333333333333',
      userAppointment : [
        { appId: 1,
          specId: '1',
          userId: '3',
          appDate: new Date(2023, 8, 26, 10, 30),
        },
        { appId: 2,
          specId: '1',
          userId: '3',
          appDate: new Date(2023, 9, 3, 10, 30),
        }
      ],
    },
    {
      userId: '4',
      userName : 'Сергеев Сергей Сергеевич',
      userBirthDate : new Date(2002, 1, 2),
      userOMS : '4444444444444444',
      userAppointment : [
        { appId: 1,
          specId: '2',
          userId: '4',
          appDate: new Date(2023, 8, 25, 13, 0),
        },
        { appId: 2,
          specId: '2',
          userId: '4',
          appDate: new Date(2023, 9, 2, 13, 0),
        }
      ],
    },
    {
      userId: '5',
      userName : 'Васильев Василий Васильевич',
      userBirthDate : new Date(1949, 8, 9),
      userOMS : '5555555555555555',
      userAppointment : [],
    },
  ];
  private resourcesData = [
    {
      resourceId: '1',
      resourceName: 'Григорьева Г.Г.',
      resourceSpec: 'Терапевт',
      resourceHospital: 'ГП №128 (к.110)',
      workTimeStart: '10:00',
      workTimeEnd: '20:00',
      workDuration: 60,
      sheduleStep: 30,
      shedule: [
        {
          day: 0,
          work: false,
          appointment: [],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 1,
          work: true,
          appointment: ['10:00', '14:00', '15:00', '20:00'],
          doesNotWork: ['14:00', '15:00'],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 2,
          work: true,
          appointment: ['10:00', '14:00', '15:00', '20:00'],
          doesNotWork: ['14:00', '15:00'],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 3,
          work: true,
          appointment: ['10:00', '14:00', '15:00', '20:00'],
          doesNotWork: ['14:00', '15:00'],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 4,
          work: true,
          appointment: ['10:00', '14:00', '15:00', '20:00'],
          doesNotWork: ['14:00', '15:00'],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 5,
          work: true,
          appointment: ['10:00', '14:00', '15:00', '20:00'],
          doesNotWork: ['14:00', '15:00'],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 6,
          work: false,
          appointment: [],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
      ],
      resourceAppointment: [
        { appId: 1,
          specId: '1',
          userId: '1',
          appDate: new Date(2023, 8, 26, 10, 0),
        },
        { appId: 2,
          specId: '1',
          userId: '2',
          appDate: new Date(2023, 8, 26, 10, 0),
        },
        { appId: 3,
          specId: '1',
          userId: '3',
          appDate: new Date(2023, 8, 26, 10, 30),
        },
        { appId: 4,
          specId: '1',
          userId: '1',
          appDate: new Date(2023, 9, 3, 10, 0),
        },
        { appId: 5,
          specId: '1',
          userId: '2',
          appDate: new Date(2023, 9, 3, 10, 0),
        },
        { appId: 6,
          specId: '1',
          userId: '3',
          appDate: new Date(2023, 9, 3, 10, 30),
        },
      ]
    },
    {
      resourceId: '2',
      resourceName: 'Сидорова С.С.',
      resourceSpec: 'Терапевт',
      resourceHospital: 'ГП №128 (к.120)',
      workTimeStart: '08:00',
      workTimeEnd: '15:00',
      workDuration: 60,
      sheduleStep: 30,
      shedule: [
        {
          day: 0,
          work: false,
          appointment: [],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 1,
          work: true,
          appointment: ['10:00', '15:00'],
          doesNotWork: [],
          holiday: false,
          learning: ['10:00', '15:00'],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 2,
          work: true,
          appointment: ['10:00', '15:00'],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 3,
          work: true,
          appointment: ['10:00', '15:00'],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 4,
          work: true,
          appointment: ['10:00', '15:00'],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 5,
          work: false,
          appointment: [],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 6,
          work: false,
          appointment: [],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
      ],
      resourceAppointment: [
        { appId: 1,
          specId: '2',
          userId: '4',
          appDate: new Date(2023, 8, 25, 13, 0),
        },
        { appId: 2,
          specId: '2',
          userId: '4',
          appDate: new Date(2023, 9, 2, 13, 0),
        },
      ]
    },
    {
      resourceId: '3',
      resourceName: 'Сидорова С.С.',
      resourceSpec: 'Терапевт',
      resourceHospital: 'ГП №128 (к.130)',
      workTimeStart: '14:00',
      workTimeEnd: '18:00',
      workDuration: 30,
      sheduleStep: 10,
      shedule: [
        {
          day: 0,
          work: false,
          appointment: [],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 1,
          work: false,
          appointment: [],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 2,
          work: false,
          appointment: [],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 3,
          work: false,
          appointment: [],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 4,
          work: false,
          appointment: [],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 5,
          work: true,
          appointment: ['14:00', '18:00'],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 6,
          work: true,
          appointment: ['14:00', '18:00'],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
      ],
      resourceAppointment: []
     },
     {
      resourceId: '4',
      resourceName: 'Елисеева Е.Е.',
      resourceSpec: 'Офтальмолог',
      resourceHospital: 'ГП №128 (к.140)',
      workTimeStart: '08:00',
      workTimeEnd: '18:00',
      workDuration: 60,
      sheduleStep: 30,
      shedule: [
        {
          day: 0,
          work: false,
          appointment: [],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 1,
          work: true,
          appointment: ['10:00', '17:45'],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: ['14:30', '14:55', '16:20', '16:40'],
          homeApp: [],
          ill: false, 
        },
        {
          day: 2,
          work: true,
          appointment: ['10:00', '17:45'],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: ['14:30', '14:55', '16:20', '16:40'],
          homeApp: [],
          ill: false, 
        },
        {
          day: 3,
          work: true,
          appointment: ['10:00', '17:45'],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: ['14:30', '14:55', '16:20', '16:40'],
          homeApp: [],
          ill: false, 
        },
        {
          day: 4,
          work: true,
          appointment: ['10:00', '17:45'],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: ['14:30', '14:55', '16:20', '16:40'],
          homeApp: [],
          ill: false, 
        },
        {
          day: 5,
          work: true,
          appointment: ['10:00', '17:45'],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: ['14:30', '14:55', '16:20', '16:40'],
          homeApp: [],
          ill: false, 
        },
        {
          day: 6,
          work: false,
          appointment: [],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
      ],
      resourceAppointment: []
     },
     {
      resourceId: '5',
      resourceName: 'Константинова-Щедрина А.А.',
      resourceSpec: 'Офтальмолог',
      resourceHospital: 'ГП №128 (к.150)',
      workTimeStart: '09:00',
      workTimeEnd: '21:00',
      workDuration: 600,
      sheduleStep: 30,
      shedule: [
        {
          day: 0,
          work: false,
          appointment: [],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 1,
          work: false,
          appointment: [],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 2,
          work: true,
          appointment: [],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 3,
          work: true,
          appointment: ['09:00', '21:00'],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 4,
          work: true,
          appointment: ['09:00', '21:00'],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 5,
          work: true,
          appointment: ['09:00', '21:00'],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
        {
          day: 6,
          work: true,
          appointment: ['09:00', '21:00'],
          doesNotWork: [],
          holiday: false,
          learning: [],
          documents: [],
          homeApp: [],
          ill: false, 
        },
      ],
      resourceAppointment: []
     },
  ]
  constructor() { }
  
  getUsersData(): Observable<any> {
    return new Observable((data) => {
      data.next(this.usersData);
        data.complete(); 
    });
  }

  getResourcesData(): Observable<any> {
    return new Observable((data) => {
      data.next(this.resourcesData);
        data.complete(); 
    });
  }

  saveData(data: any): Observable<any> {
    let flag = false;
    return new Observable((evt) => {
      this.usersData.forEach((user) => {
        if(user.userId === data.userId) {
          user = data;
          flag = true;
          evt.next(true);
          evt.complete();
        }  
      });
      if(!flag) {
        evt.error(true);
        evt.complete();
      }  
    });
  }
}
